workflows:
  react-capacitor-debug:
    name: React Capacitor Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.manglanigaurav01.prakashbhaibillbuddy"
      node: 18
      npm: 9
    cache:
      cache_paths:
        - node_modules
        - ~/.npm
        - ~/.cache/npm
        - $CM_BUILD_DIR/dist
        - $CM_BUILD_DIR/build
        - $CM_BUILD_DIR/node_modules/.vite
        - $CM_BUILD_DIR/node_modules/.cache
        - $CM_BUILD_DIR/android/.gradle
        - $CM_BUILD_DIR/android/app/build
        - ~/.gradle/caches
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build React app
        script: |
          npm run build
      - name: Setup Capacitor
        script: |
          npx cap add android
          npx cap sync android
      - name: Set Android permissions
        script: |
          chmod +x android/gradlew
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - manglanigaurav001@gmail.com
        notify:
          success: true
          failure: true
