name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build web
        run: npm run build
      - name: Archive dist
        run: |
          tar -czf web-dist.tar.gz dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            web-dist.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # APKs remain handled by Codemagic; you can attach them here by adding an upload step from Codemagic webhooks.

